### Importing libraries and preprocessed data.

In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

### Logistic regression to predict the absenteeism.

Classification of people from dataset into 'moderately absent' and 'excessively absent' based on whether below or above the median from column 'Absenteeism Time in Hours'. 

Median is chosen as it is a numerically stable method, as it implicitly balances the data into roughly two halfs and minimises the ability of the machine to focus exclusively on only one of the categories (i.e. either 1 or 0). 

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
# Creating Targets using 0 & 1 values for 'Absenteeism Time in Hours' column. 
# Excessively absent - 1, Moderately absent - 0.
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] >
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets

In [8]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [9]:
# Checking how balanced the data is.
# Here, around 46% of targets are 1, the rest is 0. 
targets.sum()/targets.shape[0]

0.45571428571428574

### Creating a checkpoint.

In [10]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis = 1)

In [11]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

### Selecting inputs for the logistic regression.

In [12]:
data_with_targets.shape

(700, 15)

In [13]:
# Removing the column with targets.
unscaled_inputs = data_with_targets.iloc[:, :-1]

In [14]:
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 14 columns]

### Standardising the data.

Applying custom scale to only chosen columns, so that dummy variables are not scaled. 

In [44]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

In [63]:
class CustomScaler (BaseEstimator, TransformerMixin):
    
    def __init__(self, columns):
        self.scaler = StandardScaler()
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, X, y = None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y = None, copy = None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns = self.columns)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis = 1)[init_col_order]

In [64]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [65]:
# Columns, which don't contain dummies. 
columns_to_scale = ['Month Value', 'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index','Children', 'Pets']

In [66]:
# Declare absenteeism scaler.
absenteeism_scaler = CustomScaler(columns_to_scale)

In [67]:
# Calculate mean and standard deviation of each 'unscaled_input'.
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\Kasia\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


CustomScaler(columns=['Month Value', 'Day of the Week',
                      'Transportation Expense', 'Distance to Work', 'Age',
                      'Daily Work Load Average', 'Body Mass Index', 'Children',
                      'Pets'])

In [68]:
# Substract mean and divide by standard deviation in order to scale the inputs.
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [70]:
# All dummies were not standardised, while the rest of the dataset was. 
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1     0.182726        -0.683704   
1           0         0         0         0     0.182726        -0.683704   
2           0         0         0         1     0.182726        -0.007725   
3           1         0         0         0     0.182726         0.668253   
4           0         0         0         1     0.182726         0.668253   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0    -0.388293        -0.007725   
696         1         0         0         0    -0.388293        -0.007725   
697         1         0         0         0    -0.388293         0.668253   
698         0         0         0         1    -0.388293         0.668253   
699         0         0         0         1    -0.388293         0.668253   

     Transportation Expense  Distance to Work       Age  \
0                  1.005844          0.412816 -0.536062   
1                 -1.574681         -1.141882  2.130803   
2                 -0.654143          1.426749  0.248310   
3                  0.854936         -1.682647  0.405184   
4                  1.005844          0.412816 -0.536062   
..                      ...               ...       ...   
695               -0.654143         -0.533522  0.562059   
696                0.040034         -0.263140 -1.320435   
697                1.624567         -0.939096 -1.320435   
698                0.190942         -0.939096 -0.692937   
699                1.036026          0.074838  0.562059   

     Daily Work Load Average  Body Mass Index  Education  Children      Pets  
0                  -0.806331         0.767431          0  0.880469  0.268487  
1                  -0.806331         1.002633          0 -0.019280 -0.589690  
2                  -0.806331         1.002633          0 -0.919030 -0.589690  
3                  -0.806331        -0.643782          0  0.880469 -0.589690  
4                  -0.806331         0.767431          0  0.880469  0.268487  
..                       ...              ...        ...       ...       ...  
695                -0.853789        -1.114186          1  0.880469 -0.589690  
696                -0.853789        -0.643782          0 -0.019280  1.126663  
697                -0.853789        -0.408580          1 -0.919030 -0.589690  
698                -0.853789        -0.408580          1 -0.919030 -0.589690  
699                -0.853789        -0.408580          0 -0.019280  0.268487  

[700 rows x 14 columns]

In [71]:
scaled_inputs.shape

(700, 14)

### Shuffle and split the data 80-20 for Training and Testing.

In [72]:
from sklearn.model_selection import train_test_split

In [73]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
 343         0         0         0         1     1.610276        -0.683704   
 118         0         0         0         1    -1.530333         0.668253   
 488         0         0         0         1     0.468236        -0.683704   
 341         0         0         0         1     1.610276        -1.359682   
 576         1         0         0         0    -1.530333         0.668253   
 ..        ...       ...       ...       ...          ...              ...   
 636         0         0         0         1    -0.959313        -1.359682   
 301         0         0         1         0     1.039256         2.020209   
 19          0         0         0         1     0.468236        -0.007725   
 395         0         0         0         1    -0.959313        -1.359682   
 113         0         0         0         1    -1.530333        -0.007725   
 
      Transportation Expense  Distance to Work       Age  \
 3

In [74]:
# Specifying some 'random_state' to ensure that the same shuffling of data will occur every time the code is executed.
# This is so that the train and test data are consistent across runs.
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [75]:
print(x_train.shape, y_train.shape)

(560, 14) (560,)


In [76]:
print(x_test.shape, y_test.shape)

(140, 14) (140,)


### Fitting the model and assessing its accuracy.

In [77]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [78]:
# Model.
reg = LogisticRegression()

In [79]:
# Fitting the model.
reg.fit(x_train, y_train)

LogisticRegression()

In [80]:
# Model accuracy.
# Model learnt to classify accurately in approx.78%. 
reg.score(x_train, y_train)

0.775

### Manually check the accuracy.

In [81]:
# Find model outputs.
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [82]:
# Display targets.
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [83]:
# Comparing the 'model_outputs' with 'y_train'.
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [84]:
# True = 1, False = 0. 
# Total number of True entries - total number of correct prediction of the model. 
np.sum((model_outputs == y_train))

434

In [85]:
# Accuracy = Correct predictions / number of observations.
np.sum((model_outputs == y_train)) / model_outputs.shape[0]

0.775

### Creating the summary table with coefficients and intercept.

It's to use the model outside the Python. 

In [86]:
# Intercept of the model.
reg.intercept_

array([-1.6561092])

In [87]:
# Coefficients of the model.
reg.coef_

array([[ 2.80096498e+00,  9.34857518e-01,  3.09561645e+00,
         8.56587468e-01,  1.66248119e-01, -8.43703301e-02,
         6.12732578e-01, -7.79685996e-03, -1.65922708e-01,
        -1.47005123e-04,  2.71811477e-01, -2.05738037e-01,
         3.61989880e-01, -2.85510745e-01]])

In [88]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [89]:
feature_name = unscaled_inputs.columns.values

In [90]:
# Creating the summary table with coefficients information.
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                  Reason_1     2.800965
1                  Reason_2     0.934858
2                  Reason_3     3.095616
3                  Reason_4     0.856587
4               Month Value     0.166248
5           Day of the Week    -0.084370
6    Transportation Expense     0.612733
7          Distance to Work    -0.007797
8                       Age    -0.165923
9   Daily Work Load Average    -0.000147
10          Body Mass Index     0.271811
11                Education    -0.205738
12                 Children     0.361990
13                     Pets    -0.285511

In [91]:
# Adding intercept to the 'summary_table'.
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index(0)
summary_table

C:\Users\Kasia\AppData\Local\Temp\ipykernel_2892\1592776086.py:4: FutureWarning: In a future version of pandas all arguments of DataFrame.sort_index will be keyword-only.
  summary_table = summary_table.sort_index(0)


Feature name  Coefficient
0                 Intercept    -1.656109
1                  Reason_1     2.800965
2                  Reason_2     0.934858
3                  Reason_3     3.095616
4                  Reason_4     0.856587
5               Month Value     0.166248
6           Day of the Week    -0.084370
7    Transportation Expense     0.612733
8          Distance to Work    -0.007797
9                       Age    -0.165923
10  Daily Work Load Average    -0.000147
11          Body Mass Index     0.271811
12                Education    -0.205738
13                 Children     0.361990
14                     Pets    -0.285511

### Interpreting the coefficients/weights

In [92]:
# Calculating the exponential value of coefficients/weights in 'Odds_ratio' column.
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [93]:
summary_table

Feature name  Coefficient  Odds_ratio
0                 Intercept    -1.656109    0.190880
1                  Reason_1     2.800965   16.460523
2                  Reason_2     0.934858    2.546851
3                  Reason_3     3.095616   22.100858
4                  Reason_4     0.856587    2.355110
5               Month Value     0.166248    1.180866
6           Day of the Week    -0.084370    0.919091
7    Transportation Expense     0.612733    1.845467
8          Distance to Work    -0.007797    0.992233
9                       Age    -0.165923    0.847112
10  Daily Work Load Average    -0.000147    0.999853
11          Body Mass Index     0.271811    1.312340
12                Education    -0.205738    0.814046
13                 Children     0.361990    1.436184
14                     Pets    -0.285511    0.751630

In [94]:
summary_table.sort_values('Odds_ratio', ascending = False)

Feature name  Coefficient  Odds_ratio
3                  Reason_3     3.095616   22.100858
1                  Reason_1     2.800965   16.460523
2                  Reason_2     0.934858    2.546851
4                  Reason_4     0.856587    2.355110
7    Transportation Expense     0.612733    1.845467
13                 Children     0.361990    1.436184
11          Body Mass Index     0.271811    1.312340
5               Month Value     0.166248    1.180866
10  Daily Work Load Average    -0.000147    0.999853
8          Distance to Work    -0.007797    0.992233
6           Day of the Week    -0.084370    0.919091
9                       Age    -0.165923    0.847112
12                Education    -0.205738    0.814046
14                     Pets    -0.285511    0.751630
0                 Intercept    -1.656109    0.190880

### Interpretation: 

Features are not particularily important if their coefficient is around 0 and odds ration around 1:
- Month Value 
- Daily Work Load Avearge
- Distance to Work 
- Day of the Week

We have 4 Reasons for absence. While creating the dummy variables for the Reasons, the Reason_0 was dropped to avoid multicollinearity. Reason_0 represented a situation where the person didn't give any particular reason for absence. Hence, the base model is when there is no reason for absence. Looking at the coefficients of Reasons 1-4, it can be said that there is a higher chance of excessive absence when there is a reason stated. 
E.g. It seems that people who report Reason_3 (poisoning) seems to be 22 times more likely to have excessive absence than people who were absent for no given reason (Reason_0).